package algos05.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static algos05.Jono.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.02.21 22:46:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JonoTest {



  // Generated by ComTest BEGIN
  /** testCountGroupsOfLetters18 */
  @Test
  public void testCountGroupsOfLetters18() {    // Jono: 18
    String p = "a"; 
    assertEquals("From: Jono line: 20", 1, countGroupsOfLetters(p)); 
    String s = "abba"; 
    assertEquals("From: Jono line: 22", 3, countGroupsOfLetters(s)); 
    String m = "aakkaacccpp"; 
    assertEquals("From: Jono line: 24", 5, countGroupsOfLetters(m)); 
  } // Generated by ComTest END
}