package algos02.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static algos02.Recursion.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.01.27 15:30:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RecursionTest {



  // Generated by ComTest BEGIN
  /** testFindSmallest21 */
  @Test
  public void testFindSmallest21() {    // Recursion: 21
    int[] t1 = { 1, 2, 3 } ; 
    int n = t1.length - 1, smallest = n; 
    assertEquals("From: Recursion line: 24", 1, findSmallest(t1, n, smallest)); 
    int[] t2 = { 4, 2, 0 } ; n = t2.length - 1; smallest = n; 
    assertEquals("From: Recursion line: 26", 0, findSmallest(t2, n, smallest)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCountZeroes57 */
  @Test
  public void testCountZeroes57() {    // Recursion: 57
    int[] t1 = { 1, 0, 3 } ; 
    int n = t1.length-1, sum = 0; 
    assertEquals("From: Recursion line: 60", 1, countZeroes(t1, n, sum)); 
    int[] t2 = { 4, 0, 0 } ; n = t2.length-1; sum = 0; 
    assertEquals("From: Recursion line: 62", 2, countZeroes(t2, n, sum)); 
  } // Generated by ComTest END
}