package algos01.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static algos01.IntDivided.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.02 14:48:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IntDividedTest {



  // Generated by ComTest BEGIN
  /** testTasanJaollinen21 */
  @Test
  public void testTasanJaollinen21() {    // IntDivided: 21
    int n = 100, m = 5; 
    assertEquals("From: IntDivided line: 23", true, tasanJaollinen(n, m)); 
    n = 10; m = 3; 
    assertEquals("From: IntDivided line: 25", false, tasanJaollinen(n, m)); 
    n = 2; m = 0; 
    assertEquals("From: IntDivided line: 27", false, tasanJaollinen(n, m)); 
  } // Generated by ComTest END
}