package algos01.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static algos01.SameCharBeginning.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.03.02 14:08:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SameCharBeginningTest {



  // Generated by ComTest BEGIN
  /** testSameChars17 */
  @Test
  public void testSameChars17() {    // SameCharBeginning: 17
    String a = "aaapuuva!"; 
    assertEquals("From: SameCharBeginning line: 19", 3, sameChars(a)); 
    String b = "b!"; 
    assertEquals("From: SameCharBeginning line: 21", 0, sameChars(b)); 
    String c = ""; 
    assertEquals("From: SameCharBeginning line: 23", 0, sameChars(c)); 
  } // Generated by ComTest END
}